name: eslint-config publish

on:
  push:
    paths:
      - "eslint/**"
      - "eslint/**/*.md"

jobs:
  publish:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: eslint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
